DROP TABLE IF EXISTS votes CASCADE;
CREATE TABLE votes ( 
  id SERIAL PRIMARY KEY NOT NULL,
  suggestion_id INTEGER REFERENCES suggestions(id) ON DELETE CASCADE,
  voter_id INTEGER REFERENCES voters(id) ON DELETE CASCADE,
  is_up_vote BOOLEAN
);